name: carrot_market_clone
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  extended_image: ^6.2.1
  logger: ^1.1.0
  beamer: ^1.4.1+1
  flutter_multi_formatter: ^2.5.7
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DoHyeon
      fonts:
        - asset: assets/fonts/BMDOHYEON_ttf.ttf
